[package]
name = "echo-service"
edition = { workspace = true }
publish = false

[dependencies]
bytes = "1"
prost = "0.14"
tonic = "0.14"
prost-types = "0.14"
tonic-prost = "0.14.3"

[build-dependencies]
tonic-prost-build = "0.14"
