[package]
name = "echo-service"
edition = { workspace = true }
publish = false

[dependencies]
bytes = "1"
prost = { workspace = true }
tonic = { workspace = true }
prost-types = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
